### PR TITLE
[WIP] GiST support

### PR DESCRIPTION
**Pull request by zachasme**
We have implemented basic SP-GiST support.

We are going to experiment with regular GiST index support on this branch as well.

### CODE REVIEW

**Comment by AbelVM** [comment]
**How can we help?** :hammer:

**Comment by zachasme** [comment]
If I recall correctly, the state of the branch (which hasn't been touched in a year :open_mouth:) is that we managed to get GiST and SP-GiST operator classes to compile and run. However, tests either returned wrong results or were significantly slower than no index. There probably is either a logical error or a misimplementation of (SP-)GiST.

Help is very much welcomed!

The branch should be rebased (or maybe it's easier to simply copy the opclass since so much has changed). Then, we need to figure out what is wrong with our implementation. My implementation is based off the [SP-GiST docs](https://www.postgresql.org/docs/current/spgist-extensibility.html) and [GiST docs](https://www.postgresql.org/docs/current/gist-extensibility.html) but if anyone has some other reference implementation that could be helpful.

**Comment by AbelVM** [comment]
Roger that. Let's move the conversation to the linked issue!

**Comment by zachasme** [comment]
Closing in favor of #42.

**Pull request closed without merging**
