### PR TITLE
Split h3 polygons by 180th meridian

### PR DESCRIPTION
**Pull request by mngr777**
This change allows `h3_cell_to_boundary_geometry` and `h3_cell_to_boundary_geography`
functions to split H3 polygons instead of extending their coordinates when crossing
180th meridian. Simple WKB encoder had to be added since Postgres does not support
multipolygones.

Split points are calculated by intersecting great circles containing boundary segment and 0/180 meridians.

## Examples:

* at equator:
```
# SELECT ST_AsText( h3_cell_to_boundary_geography(h3_lat_lng_to_cell(POINT(180, 0), 1), true) );
MULTIPOLYGON(((-180 -1.192096049620255,-178.7982364398432 -0.936163764598355,-178.0251966524985 2.904037450579835,-180 5.045920018717693,-180 -1.192096049620255)),((175.46041201203371 4.24859231701783,175.0938278791749 0.849947565248796,176.15596775399112 0.277783583991809,177.85728757138185 -1.646918936422032,180 -1.192096049620255,180 5.045920018717693,179.21716082489448 5.889921754313913,175.46041201203371 4.24859231701783)))
```
split-equator

* North Pole:
```
# SELECT ST_AsText( h3_cell_to_boundary_geography(h3_lat_lng_to_cell(POINT(0, 90), 1), true) );
MULTIPOLYGON(((-180 86.32085543087278,-161.8917180108592 84.22628942426208,-125.29445893479551 82.48154130920916,-90.38109747487815 82.85349004122665,-51.704877515308034 84.93555635380535,0 87.77372183376991,-180 86.32085543087278)),((8.384360674740835 87.82361750161175,145.5581976913368 87.3646953231962,180 86.32085543087278,0 87.77372183376991,8.384360674740835 87.82361750161175)))
```
split-north-pole

* South Pole:
```
# SELECT ST_AsText( h3_cell_to_boundary_geography(h3_lat_lng_to_cell(POINT(0, -90), 1), true) );
MULTIPOLYGON(((0 -88.9010571803527,-34.441802308663334 -87.3646953231962,-87.34455122467276 -84.24413301148068,-124.07451529163794 -82.50396355374559,-159.09074448175286 -82.87200197672588,-180 -84.48417730028918,0 -88.9010571803527)),((162.09183616506846 -84.94207431820979,101.81683545801506 -87.80824356139675,0 -88.9010571803527,180 -84.48417730028918,162.09183616506846 -84.94207431820979)))
```
split-south-pole

### CODE REVIEW

**Review by Komzpa — APPROVED** [review]
Such a change simplifies dealing with global datasets a lot.

**Comment by zachasme** [comment]
This is very nice! It could probably completely replace the `extend_at_meridian` functionality I made.

Would you ever use `h3_cell_to_boundary_wkb` on its own, or only through the PostGIS functions? Otherwise we might try and add a `h3_cell_to_boundaries` that returns a (native postgres) polygon array, to see if I can avoid the WBK encoder.

**Comment by Komzpa** [comment]
With my PostGIS PSC hat on: (E)WKB in a bytea is officially recommended way to plug geometry-emitting extensions into PostGIS. If it's not conflicting with other goals of the extension it should be embraced compared to native geometry datatypes.

**Comment by zachasme** [comment]
I am mostly using `h3-pg` for a project without PostGIS installed, yet I suppose most people will be using the extension alongside PostGIS.

Anyway, that is the reason I am hesitant to merge PostGIS related functionality into the main extension. But until I figure out a way to include c code for the extra extension I'm open to merging this as it is.

Thank you for the contribution @mngr777!

**Pull request merged**
